# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{ replace_with 0 "generated_header" }}

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    duck.knative.dev/source: "true"
    events.cloud.google.com/release: devel
    events.cloud.google.com/crd-install: "true"
  annotations:
    registry.knative.dev/eventTypes: |
      [
        { "type": "com.google.cloud.pubsub.topic.publish", "description": "This event is sent when a message is published to a Cloud Pub/Sub topic."}
      ]
  name: cloudpubsubsources.events.cloud.google.com
spec:
  group: events.cloud.google.com
  names:
    categories:
    - all
    - knative
    - cloudpubsubsource
    - sources
    kind: CloudPubSubSource
    plural: cloudpubsubsources
  scope: Namespaced
  subresources:
    status: {}
  preserveUnknownFields: false
  additionalPrinterColumns:
    {{- replace_with 4 "ready_reason_age" }}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - sink
            - topic
          properties:
            {{- replace_with 12 "pubsub_spec" }}
            topic:
              type: string
              description: >
                ID of the Cloud Pub/Sub Topic to Subscribe to. It must be in the form of the unique
                identifier within the project, not the entire name. E.g. it must be 'laconia', not
                'projects/my-gcp-project/topics/laconia'.
            ackDeadline:
              type: string
              description: >
                The default maximum time after a subscriber receives a message before the subscriber
                should acknowledge the message. Defaults to `30s`. Valid time units are `s`, `m`,
                `h`. The minimum deadline you can specify is 0 seconds. The maximum deadline you can
                specify is 600 seconds (10 minutes).
            retainAckedMessages:
              type: boolean
              description: >
                Whether to retain acknowledged messages. If true, acknowledged messages will not be
                expunged until they fall out of the RetentionDuration window.
            retentionDuration:
              type: string
              description: >
                How long to retain messages in backlog, from the time of publish. If
                retainAckedMessages is true, this duration affects the retention of acknowledged
                messages, otherwise only unacknowledged messages are retained. Defaults to 7 days
                (`168h`). Cannot be longer than 7 days or shorter than 10 minutes. Valid time units
                are `s`, `m`, `h`.
        status:
          type: object
          properties:
            {{- replace_with 12 "pubsub_status" }}
