apiVersion: events.cloud.google.com/v1beta1
kind: CloudAuditLogsSource
metadata:
  name: cloudauditlogssource-test
spec:
  serviceName: pubsub.googleapis.com
  methodName: google.pubsub.v1.Publisher.CreateTopic
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display

#    # If running in GKE, we will ask the metadata server, change this if required.
#  project: MY_PROJECT
#    # If running with workload identity enabled, update serviceAccountName.
#  serviceAccountName: kubernetes-service-account-name
#    # If running with secret, here is the default secret name and key, change this if required.
#  secret:
#    name: google-cloud-key
#    key: key.json
