- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties
  value:
    sink:
      type: object
      description: >
        Sink which receives the notifications.
      properties:
        uri:
          type: string
          minLength: 1
        ref:
          type: object
          required:
            - apiVersion
            - kind
            - name
          properties:
            apiVersion:
              type: string
              minLength: 1
            kind:
              type: string
              minLength: 1
            namespace:
              type: string
            name:
              type: string
              minLength: 1
    ceOverrides:
      type: object
      description: >
        Defines overrides to control modifications of the event sent to the sink.
      properties:
        extensions:
          type: object
          description: >
            Extensions specify what attribute are added or overridden on the outbound event. Each
            `Extensions` key-value pair are set on the event as an attribute extension independently.
          x-kubernetes-preserve-unknown-fields: true
    googleServiceAccount:
      type: string
      description: >
        GCP service account used to poll the Cloud Pub/Sub Subscription. The value of the service
        account must be a valid Google service account (see
        https://cloud.google.com/iam/docs/service-accounts)."
    secret:
      type: object
      description: >
        Credential used to poll the Cloud Pub/Sub Subscription. It is not used to create or delete the
        Subscription, only to poll it. The value of the secret entry must be a service account key in
        the JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).
        Defaults to secret.name of 'google-cloud-key' and secret.key of 'key.json'."
      properties:
        name:
          type: string
        key:
          type: string
        optional:
          type: boolean
    project:
      type: string
      description: >
        Google Cloud Project ID of the project into which the topic should be created. If omitted uses
        the Project ID from the GKE cluster metadata service.

