name: Check and Update
on: pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-go@v2.1.0
      with:
        go-version: 1.14.4
    # Runs a single command using the runners shell
    - name: gofmt
      run: find -name '*.go' -type f \! -name '*.pb.go' -exec gofmt -s -w {} \+ -o \( -path './vendor' -o -path './third_party' \) -prune
    - name: goimports
      run: |
        go get golang.org/x/tools/cmd/goimports
        find -name '*.go' \! -name wire_gen.go \! -name '*.pb.go' -exec goimports -w {} \+ -o \( -path ./vendor -o -path ./third_party \) -prune
    - uses: EndBug/add-and-commit@v4.2.0
      with:
        message: "Format go"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
